services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./configs/cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - cloudflared_creds:/home/nonroot/.cloudflared
    network_mode: host
    user: "1000:1000"

volumes:
  cloudflared_creds:
